DROP TABLE ETUDIANT;
CREATE TABLE ETUDIANT (
 id NUMBER PRIMARY KEY,
 nom VARCHAR2(50),
 note NUMBER
);

INSERT INTO ETUDIANT VALUES (1,'Ali',14);
INSERT INTO ETUDIANT VALUES (2,'Sara',10);
INSERT INTO ETUDIANT VALUES (3,'Youssef',8);
INSERT INTO ETUDIANT VALUES (4,'Lina',16);
COMMIT;